$linkedData:
  term: SIMASteelImportLicenseApplicationCredential
  '@id': https://w3id.org/traceability#SIMASteelImportLicenseApplicationCredential
title: SIMA Steel Import License Application Credential
tags:
  - Steel
description: Steel Import Monitoring and Analysis Licensing Application based on https://www.trade.gov/us-industry-licensing.
type: object
properties:
  '@context':
    type: array
    readOnly: true
    const:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    default:
      - https://www.w3.org/2018/credentials/v1
      - https://w3id.org/traceability/v1
    items:
      type: string
      enum:
        - https://www.w3.org/2018/credentials/v1
        - https://w3id.org/traceability/v1
  type:
    type: array
    readOnly: true
    const:
      - VerifiableCredential
      - SIMASteelImportLicenseApplicationCredential
    default:
      - VerifiableCredential
      - SIMASteelImportLicenseApplicationCredential
    items:
      type: string
      enum:
        - VerifiableCredential
        - SIMASteelImportLicenseApplicationCredential
  id:
    type: string
    format: uri
  issuanceDate:
    description: Date of Application
    type: string
    format: date-time
  issuer:
    title: Applicant Company
    description: Organization issuing the SIMA Import License Application
    type: object
    properties:
      type:
        type: array
        readOnly: true
        const:
          - Organization
        default:
          - Organization
        items:
          type: string
          enum:
            - Organization
      id: 
        title: Identifier
        description: Organization identifier.
        type: string
        format: uri
      name:
        title: Name
        description: Name of the organization.
        type: string
      location:
        title: Location
        description: The location where, for example, an event is happening, an organization is located, or an action takes place.
        type: object
        properties:
          type:
            type: array
            readOnly: true
            const:
              - Place
            default:
              - Place
            items:
              type: string
              enum:
                - Place
          address:
            title: Postal Address
            description: The postal address for an organization or place.
            type: object
            properties:
              type:
                type: array
                readOnly: true
                const:
                  - PostalAddress
                default:
                  - PostalAddress
                items:
                  type: string
                  enum:
                    - PostalAddress
              streetAddress:
                title: Street Address
                description: >-
                  The street address expressed as free form text. The street address is
                  printed on paper as the first lines below the name. For example, the name
                  of the street and the number in the street, or the name of a building.
                type: string
              addressLocality:
                title: Address Locality
                description: Text specifying the name of the locality; for example, a city.
                type: string
              addressRegion:
                title: Address Region
                description: >-
                  Text specifying a province or state in abbreviated format; for example,
                  NJ.
                type: string
              addressCountry:
                title: Address Country
                description: >-
                  The two-letter ISO 3166-1 alpha-2 country code.
                type: string
              postalCode:
                title: Postal Code
                description: Text specifying the postal code for an address.
                type: string
            additionalProperties: false
            required:
              - type
      email:
        title: Contact Address
        description: Contact email address.
        type: string
      phoneNumber:
        title: Contact Phone
        description: Organization's contact phone number.
        type: string
      faxNumber:
        title: Contact Fax
        description: Organ$ization's fax number.
        type: string
    additionalProperties: false
    required:
      - type
      - id
  credentialSchema:
    type: object
    properties:
      id:
        title: Id
        description: The url of the schema file to validate the shape of the json object
        type: string
        format: uri
        example: https://w3id.org/traceability/openapi/components/schemas/credentials/SIMASteelImportLicenseApplicationCredential.yml
        default: https://w3id.org/traceability/openapi/components/schemas/credentials/SIMASteelImportLicenseApplicationCredential.yml
        readOnly: true
      type:
        title: Type
        description: The type of validation to be run against the defined schema
        const: OpenApiSpecificationValidator2022
  credentialSubject:
    title: Application Details
    description: SIMA steel import license application details.
    type: object
    properties:
      type:
        type: array
        readOnly: true
        const:
          - SIMASteelImportLicense
        default:
          - SIMASteelImportLicense
        items:
          type: string
          enum:
            - SIMASteelImportLicense
      customsEntryNumber:
        title: Customs Entry Number
        description: Input if known at time of application. This number is optional.
        type: string
      importer:
        title: Importer
        description: Name of Importer of Record.
        type: object
        properties:
          type:
            type: array
            readOnly: true
            const:
              - Organization
            default:
              - Organization
            items:
              type: string
              enum:
                - Organization
          id: 
            title: Identifier
            description: Organization identifier.
            type: string
            format: uri
          name:
            title: Name
            description: Name of the organization.
            type: string
        required:
          - type
          - name
      exporter:
        title: Exporter
        description: Name of Exporter.
        type: object
        properties:
          type:
            type: array
            readOnly: true
            const:
              - Organization
            default:
              - Organization
            items:
              type: string
              enum:
                - Organization
          id: 
            title: Identifier
            description: Organization identifier.
            type: string
            format: uri
          name:
            title: Name
            description: Name of the organization.
            type: string
        required:
          - type
          - name
      manufacturer:
        title: Manufacturer
        description: Name of manufacturer(s) of the product(s) or shipper(s). May list multiple manufacturers or as unknown.
        type: object
        properties:
          type:
            type: array
            readOnly: true
            const:
              - Organization
            default:
              - Organization
            items:
              type: string
              enum:
                - Organization
          id: 
            title: Identifier
            description: Organization identifier.
            type: string
            format: uri
          name:
            title: Name
            description: Name of the organization.
            type: string
        required:
          - type
          - name
      countryOfOrigin:
        title: Country of Origin
        description: Country in which the product(s) were manufactured. The two-letter ISO 3166-1 alpha-2 country code.
        type: string
      countryOfExportation:
        title: Country of Exportation
        description: Country from which the product(s) were exported. The two-letter ISO 3166-1 alpha-2 country code.
        type: string
      expectedPortOfEntry:
        title: Expected Port of Entry
        description: Expected port of entry.
        type: string
      expectedDateOfExport:
        title: Expected Date of Export
        description: Date product(s) expected to be shipped from the country of exportation.
        type: string
        format: date-time
      expectedDateOfImport:
        title: Expected Date of Import
        description: Date product(s) expected to be shipped from the country of exportation.
        type: string
        format: date-time
      productInformation:
        title: Product Information
        description: Steel products applied for licensing.
        type: array
        minItems: 1
        items:
          title: Steel Product
          description: Steel product details.
          type: object
          properties:
            type:
              type: array
              readOnly: true
              const:
                - SIMASteelImportProductSpecifier
              default:
                - SIMASteelImportProductSpecifier
              items:
                type: string
                enum:
                  - SIMASteelImportProductSpecifier
            commodity:
              title: Commodity
              description: Product commodity code, codification system and description
              type: object
              properties:
                type:
                  type: array
                  readOnly: true
                  const:
                    - Commodity
                  default:
                    - Commodity
                  items:
                    type: string
                    enum:
                      - Commodity
                commodityCode:
                  title: Commodity Code
                  description: >-
                    The 10-digit HTS commodity code.
                  type: string
                  $linkedData:
                    term: commodityCode
                    '@id': https://w3id.org/traceability#commodityCode
                commodityCodeType:
                  title: Commodity Code Type
                  description: Commodity code type
                  enum:
                    - HTS
                  $linkedData:
                    term: commodityCodeType
                    '@id': https://w3id.org/traceability#commodityCodeType
                description:
                  title: Commodity Description
                  description: Description of the commodity.
                  type: string
                  $linkedData:
                    term: description
                    '@id': https://schema.org/description
            productCategory:
              title: Product Category
              description: Category assigned to the product based on the Product HTS. 
              type: string
            countryOfMeltAndPour:
              title: Country of Melt And Pour
              description: Modified regulations pertaining to the Steel Import Monitoring and Analysis (SIMA) system to require steel import license applicants to identify the country where the steel used in the manufacture of the imported steel product was melted and poured (https://www.govinfo.gov/content/pkg/FR-2020-09-11/html/2020-19753.htm). The two-letter ISO 3166-1 alpha-2 country code.
              type: string
            weight:
              title: Weight
              description: Volume (Quantity - KG)
              type: object
              properties:
                type:
                  type: array
                  readOnly: true
                  const:
                    - MeasuredValue
                  default:
                    - MeasuredValue
                  items:
                    type: string
                    enum:
                      - MeasuredValue
                value:
                  title: Measurement Value
                  description: >-
                    A floating-point numeric value that is qualified by the corresponding
                    measurement unit code - see gs1:unitCode.
                  type: string
                  $linkedData:
                    term: value
                    '@id': https://schema.org/value
                unitCode:
                  title: Measurement Unit
                  description: Product weight must be provided in kilograms on the SIMA Application. 
                  type: string
                  enum: 
                    - KGM
                  $linkedData:
                    term: unitCode
                    '@id': https://schema.org/unitCode
            customsValue:
              title: Customs Value
              description: Entered value of this product in U.S. dollars; not invoiced value (It should not include duty, brokerage fees, or freight).
              type: object
              properties:
                type:
                  type: array
                  readOnly: true
                  const:
                    - MonetaryAmount
                  default:
                    - MonetaryAmount
                  items:
                    type: string
                    enum:
                      - MonetaryAmount
                value:
                  title: Value
                  description: >-
                    Use values from 0123456789. Use '.' rather than ',' to indicate a decimal point. Avoid using these symbols as a readability separator.
                  type: number
                currency:
                  title: Currency
                  description: >-
                    The currency in which the monetary amount is expressed. Use standard formats: ISO 4217 currency format, e.g. "USD".
                  type: string
                  enum: 
                    - USD
              additionalProperties: false
              required:
                - type
                - value
                - currency
          additionalProperties: false
          required:
            - type
            - commodity
            - countryOfMeltAndPour
            - weight
            - customsValue
    additionalProperties: false
    required:
      - type
      - importer
      - exporter
      - manufacturer
      - countryOfOrigin
      - countryOfExportation
      - productInformation
  proof:
    title: proof
    description: A JSON Web Signature proof for a credential as defined by the VC data model 
    type: object
    properties:
      type:
        type: string
        description: Signature suite for the proof
        enum:
          - Ed25519Signature2018
      created:
        description: Creation timestamp for the proof in the form of an XML datestring
        type: string
      verificationMethod:
        description: The fragment from which the public key can be de-referenced, in the form of a URI
        type: string
      proofPurpose:
        description: In the case of credentials, the proof should be the constant, 'assertionMethod'
        const: assertionMethod
      jws:
        description: The JSON Web Signature for the proof
        type: string
additionalProperties: false
required:
  - '@context'
  - type
  - id
  - issuanceDate
  - issuer
  - credentialSubject
example: |-
  {
    "@context": [
      "https://www.w3.org/2018/credentials/v1",
      "https://w3id.org/traceability/v1"
    ],
    "id": "did:key:z6MknrcKsbzfy6kKFxtJQHxq43zHofhBuUqB6QGvvqF6FX7c",
    "type": [
      "VerifiableCredential",
      "SIMASteelImportLicenseApplicationCredential"
    ],
    "issuer": {
      "type": [
        "Organization"
      ],
      "id": "did:key:z6MktHQo3fRRohk44dsbE76CuiTpBmyMWq2VVjvV6aBSeE3U",
      "name": "Maxi Acero Mexicano",
      "location": {
        "type": [
          "Place"
        ],
        "address": {
          "type": [
            "PostalAddress"
          ],
          "streetAddress": "Avenida Carlos 100",
          "addressLocality": "Hern√°dez de Mara",
          "addressRegion": "Nuevo Leon",
          "postalCode": "32200",
          "addressCountry": "Mexico"
        }
      }
    },
    "issuanceDate": "2023-02-28T11:23:00Z",
    "credentialSubject": {
      "type": [
        "SIMASteelImportLicense"
      ],
      "customsEntryNumber": "34001239",
      "importer": {
        "type": [
          "Organization"
        ],
        "name": "American Prime Steel Inc."
      },
      "exporter": {
        "type": [
          "Organization"
        ],
        "name": "Maxi Acero Mexicano"
      },
      "manufacturer": {
        "type": [
          "Organization"
        ],
        "name": "Maxi Acero Mexicano"
      },
      "countryOfOrigin": "MX",
      "countryOfExportation": "MX",
      "expectedPortOfEntry": "USMOB",
      "expectedDateOfExport": "2022-04-02T08:00:00Z",
      "expectedDateOfImport": "2022-04-09T10:30:00Z",
      "productInformation": [
        {
          "type": [
            "SIMASteelImportProductSpecifier"
          ],
          "commodity": {
            "type": [
              "Commodity"
            ],
            "commodityCode": "7207200075",
            "commodityCodeType": "HTS",
            "description": "SEMIFINISHED IRON/NONALLOW STL"
          },
          "productCategory": "Blooms, Billets and Slabs",
          "countryOfMeltAndPour": "AR",
          "weight": {
            "type": [
              "MeasuredValue"
            ],
            "value": "10000",
            "unitCode": "KGM"
          },
          "customsValue": {
            "type": [
              "MonetaryAmount"
            ],
            "value": 24000,
            "currency": "USD"
          }
        }
      ]
    }
  }